### ISSUE TITLE
Incorrect highlighting after method definition with end of line comment

### ISSUE THREAD

**Issue by noniq** [textmate/ruby.tmbundle#103]
Example to reproduce:

```
def foo(_) #
  ["a", "b"]
end
```

Screenshot: 
![bildschirmfoto 2016-08-08 um 19 12 36](https://cloud.githubusercontent.com/assets/244158/17488965/14ff8e1c-5d9c-11e6-93c5-d7f7087cf366.png)

Does not happen if the comment sign is removed, if there are no parens around the method argument, or if there are no method arguments at all.

**Comment by noniq** [comment]
It seems this can be fixed by changing the regexp for matching the end of the argument list (line 158) from `(?=,|\)\s*$)` to `(?=,|\)\s*($|#))`, but not sure if this causes unwanted side effects.

**Comment by infininight** [comment]
Fixed, thanks for the report!
