### ISSUE TITLE
incorrect indentation when using String#scan with block

### ISSUE THREAD

**Issue by tkosaka1976** [textmate/ruby.tmbundle#108]
When we use String#scan then indentation like this  
```ruby
"Test".scan(/e/) do |c|  
data << [c, Regexp.last_match.offset(0).first]  
end
```
  
but should be   
```ruby
"Test".scan(/e/) do |c|    
    data << [c, Regexp.last_match.offset(0).first]    
end
```

**Comment by infininight** [comment]
Unable to reproduce this issue, I get the second when I run the indent command or type this manually. You are using 2.0 of TextMate and have bundle updates enabled?

**Comment by tkosaka1976** [comment]
Sorry. Probably now it was solved.
I also using 2.0-rc.4 with latest bundle.
Thanks!
