### ISSUE TITLE
XML Heredoc

### ISSUE THREAD

**Issue by jish** [textmate/ruby.tmbundle#111]
I came here to investigate how I could add XML Heredoc support, and I found this recent commit which I think addresses the problem I am having https://github.com/textmate/ruby.tmbundle/commit/bf1a0e525a28188012acb4612b730f20b7d3ff6e.

But I still do not see XML Heredoc highlighting. What am I doing wrong? How can I add this support?

```ruby
xml = <<-XML
  <foo>
    <bar>string</bar>
  </foo>
XML

html = <<-HTML
  <foo>
    <bar>string</bar>
  </foo>
HTML
```

**Comment by jish** [comment]
Is it possible to get `XML` highlighting in Ruby heredoc, or am I mis-reading something?

**Comment by infininight** [comment]
This was added in the grammar but it had not been deployed, it has now been deployed and your bundle should update within a few hours.
