### ISSUE TITLE
Can't use Reformat Document

### ISSUE THREAD

**Issue by flyweights** [textmate/ruby.tmbundle#128]
I am a newbie using textmate, I want to use Reformat Document, but it reported an error, I used Google search for a long time, still did not find a way to solve. As is shown in:
![image](https://user-images.githubusercontent.com/12111609/56433657-3911d600-6304-11e9-9b27-c2f404ebb6b7.png)

**Comment by noniq** [comment]
Thanks for the report! This should be fixed now. (It might take some time for your copy of the bundle to update automatically.)
