### ISSUE TITLE
Run Focused Unit Test question

### ISSUE THREAD

**Issue by beny** [textmate/ruby.tmbundle#64]
Why there are so many arguments in `run_script.rb` for running minitest's spec at line 33:

`args << %Q{--name="/test_spec \\{.*#{context}\\} \\d{3} \\[#{spec}\\]/"}`

Does it actually work for someone or am I just using it wrong? It just does not work with curren Ruby version (ruby 2.1.0p0) for me. When I change it to just  

`args << "--name=/#{context}/"`

it works like a charm.

Am I missing something?

**Comment by noniq** [comment]
Is this still an issue, @beny? If yes, could you provide an example test file to reproduce the error?

**Comment by noniq** [comment]
Closing because it seems stale.
