### ISSUE TITLE
Multiline statements lack styling

### ISSUE THREAD

**Issue by elifoster** [textmate/ruby.tmbundle#87]
I reported this at github/linguist#2692, and was told to report it here. We're unsure if it is actually a text mate issue, but that is what is suspected. I'm not really familiar with TextMate itself, but there should be sufficient information in that issue.

**Comment by infininight** [comment]
Corrected, thanks for the report.

Note: This will be reflected in TextMate later today but will not show up on Github until the next update of linguist which which happens every few weeks.
