### ISSUE TITLE
CMD+R Error on Textmate2

### ISSUE THREAD

**Issue by caiwenhn2008** [textmate/ruby.tmbundle#92]
HI, there is an issue by running cmd+R on Textmate2

error log: 
No web preview theme found.
Make sure that the Themes bundle is enabled in Preferences->Bundles

**Comment by sorbits** [comment]
You already reported this as textmate/shellscript.tmbundle#27 but it is 
not a bundle issue.

**Comment by sorbits** [comment]
Closing due to lack of follow-up and presumably a local problem.
