### ISSUE TITLE
Go to symbol (Cmd+Shift+T) is broken

### ISSUE THREAD

**Issue by yukas** [textmate/ruby.tmbundle#97]
TextMate version 2.0-beta.9

<img width="770" alt="screen shot 2016-05-12 at 5 32 53 pm" src="https://cloud.githubusercontent.com/assets/178645/15218225/9723aa74-1867-11e6-9361-8e9dba5dc5c8.png">

**Comment by sorbits** [comment]
Likely a local problem, for troubleshooting see this post http://lists.macromates.com/textmate/2016-May/039464.html
